name: ci_check

on:
  push:
    branches:
      - dev
      - master
      - go-rewrite

  pull_request:
    branches:
      - dev
      - master
      - go-rewrite

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install libxrandr (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install xorg-dev

      - name: Go tidy
        run: go mod tidy

      - name: Test
        run: go build -o bin/test/test test/test1/test.go 
